In [2]:
import pandas as pd

In [3]:
df_contaminacion = pd.read_csv("datos_contaminacion_finales.csv")
df_contaminacion

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,Partículas<10,Óxidos de Nitrógeno,Ozono,Tolueno,Benceno,Etilbenceno,HidrocarburosTot,Metano,HidrocarburosNoMet
0,4,2013,7,1,1,5.0,0.5,48.0,112.0,0.0,0.0,186.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4,2013,7,1,2,5.0,0.6,79.0,116.0,0.0,0.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4,2013,7,1,3,4.0,0.3,6.0,47.0,0.0,0.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,2013,7,1,4,3.0,0.2,3.0,25.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,2013,7,1,5,3.0,0.2,3.0,10.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405203,60,2024,12,31,20,0.0,0.0,16.0,65.0,0.0,21.0,90.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
2405204,60,2024,12,31,21,0.0,0.0,33.0,77.0,0.0,35.0,128.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2405205,60,2024,12,31,22,0.0,0.0,29.0,68.0,0.0,30.0,112.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
2405206,60,2024,12,31,23,0.0,0.0,7.0,47.0,0.0,22.0,57.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0
2405207,60,2024,12,31,24,0.0,0.0,3.0,36.0,0.0,20.0,40.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df_trafico = pd.read_csv("datos_trafico.csv", dtype={0: str})
df_trafico

            id  intensidad   año  mes  dia  hora
0        04002      143.75  2013    7    1     0
1        04002       78.75  2013    7    1     1
2        04002       86.75  2013    7    1     2
3        04002       39.25  2013    7    1     3
4        04002       13.50  2013    7    1     4
...        ...         ...   ...  ...  ...   ...
1829463  11038      397.75  2024   12   31    19
1829464  11038      387.50  2024   12   31    20
1829465  11038      308.25  2024   12   31    21
1829466  11038      153.00  2024   12   31    22
1829467  11038       80.25  2024   12   31    23

[1829468 rows x 6 columns]

In [5]:
df_clima = pd.read_csv("datos_clima.csv")
df_clima

,Año,Mes,Dia,Hora,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,2013,1,1,0,1.40,1.06,1.23,97.43,11.87,92.77,2.38,214.6
1,2013,1,1,1,1.13,0.83,0.98,97.72,10.04,92.71,2.03,219.2
2,2013,1,1,2,0.96,0.67,0.82,97.99,5.90,92.68,1.59,231.9
3,2013,1,1,3,1.05,0.79,0.92,98.00,1.85,92.66,1.21,252.6
4,2013,1,1,4,1.00,0.91,0.95,99.27,0.85,92.67,0.86,273.3
...,...,...,...,...,...,...,...,...,...,...,...,...
105187,2024,12,31,19,3.60,-1.34,1.13,70.20,0.00,93.80,1.17,11.3
105188,2024,12,31,20,2.58,-1.86,0.36,72.42,0.00,93.83,1.26,26.4
105189,2024,12,31,21,1.92,-2.30,-0.19,73.36,0.00,93.85,1.28,40.9
105190,2024,12,31,22,1.45,-2.50,-0.52,74.79,0.00,93.88,1.26,54.7
105191,2024,12,31,23,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5

In [6]:
#Me he dado cuenta que los datos del clima van de 0 a 23 a 23 en vez de 1 a 24, para arreglar esto quitare la primera fila subiendo la columna una posicion del df y cambiare los 0 por 24
df_clima[["Hora","Temperatura","PuntoRocio","TempHumeda","HumedadRelativa", "Precipitacion","Presion","VelViento","DirViento"]] = df_clima[["Hora","Temperatura","PuntoRocio","TempHumeda","HumedadRelativa", "Precipitacion","Presion","VelViento","DirViento"]].shift(-1)
df_clima["Hora"] = df_clima["Hora"].replace(0, 24)

In [7]:
df_clima

,Año,Mes,Dia,Hora,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,2013,1,1,1.0,1.13,0.83,0.98,97.72,10.04,92.71,2.03,219.2
1,2013,1,1,2.0,0.96,0.67,0.82,97.99,5.90,92.68,1.59,231.9
2,2013,1,1,3.0,1.05,0.79,0.92,98.00,1.85,92.66,1.21,252.6
3,2013,1,1,4.0,1.00,0.91,0.95,99.27,0.85,92.67,0.86,273.3
4,2013,1,1,5.0,0.79,0.93,0.86,100.00,0.66,92.70,0.90,293.7
...,...,...,...,...,...,...,...,...,...,...,...,...
105187,2024,12,31,20.0,2.58,-1.86,0.36,72.42,0.00,93.83,1.26,26.4
105188,2024,12,31,21.0,1.92,-2.30,-0.19,73.36,0.00,93.85,1.28,40.9
105189,2024,12,31,22.0,1.45,-2.50,-0.52,74.79,0.00,93.88,1.26,54.7
105190,2024,12,31,23.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5
105191,2024,12,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#Para completar la fila de NaN que queda en el ultimo registro de datos climatologicos la relleno con los mismos valores que fila anterior 
df_clima = df_clima.ffill()
#Arreglo la hora
df_clima.loc[df_clima.index[-1], "Hora"] = 24

In [9]:
df_clima

,Año,Mes,Dia,Hora,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,2013,1,1,1.0,1.13,0.83,0.98,97.72,10.04,92.71,2.03,219.2
1,2013,1,1,2.0,0.96,0.67,0.82,97.99,5.90,92.68,1.59,231.9
2,2013,1,1,3.0,1.05,0.79,0.92,98.00,1.85,92.66,1.21,252.6
3,2013,1,1,4.0,1.00,0.91,0.95,99.27,0.85,92.67,0.86,273.3
4,2013,1,1,5.0,0.79,0.93,0.86,100.00,0.66,92.70,0.90,293.7
...,...,...,...,...,...,...,...,...,...,...,...,...
105187,2024,12,31,20.0,2.58,-1.86,0.36,72.42,0.00,93.83,1.26,26.4
105188,2024,12,31,21.0,1.92,-2.30,-0.19,73.36,0.00,93.85,1.28,40.9
105189,2024,12,31,22.0,1.45,-2.50,-0.52,74.79,0.00,93.88,1.26,54.7
105190,2024,12,31,23.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5
105191,2024,12,31,24.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5

In [10]:
#Para conectarlos hare un merge, los datos de trafico aun no estan tratados del todo pero los de clima y contaminacion si
df_clima_contaminacion = pd.merge(df_contaminacion, df_clima, on=["Año", "Mes", "Dia", "Hora"], how="left")

In [11]:
df_clima_contaminacion

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,Metano,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,4,2013,7,1,1,5.0,0.5,48.0,112.0,0.0,...,0.0,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0
1,4,2013,7,1,2,5.0,0.6,79.0,116.0,0.0,...,0.0,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6
2,4,2013,7,1,3,4.0,0.3,6.0,47.0,0.0,...,0.0,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6
3,4,2013,7,1,4,3.0,0.2,3.0,25.0,0.0,...,0.0,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5
4,4,2013,7,1,5,3.0,0.2,3.0,10.0,0.0,...,0.0,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405203,60,2024,12,31,20,0.0,0.0,16.0,65.0,0.0,...,0.0,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4
2405204,60,2024,12,31,21,0.0,0.0,33.0,77.0,0.0,...,0.0,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9
2405205,60,2024,12,31,22,0.0,0.0,29.0,68.0,0.0,...,0.0,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7
2405206,60,2024,12,31,23,0.0,0.0,7.0,47.0,0.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5
2405207,60,2024,12,31,24,0.0,0.0,3.0,36.0,0.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5

In [12]:
df_clima_contaminacion[df_clima_contaminacion.Temperatura.isna()]

Empty DataFrame
Columns: [Estación, Año, Mes, Dia, Hora, Dióxido de Azufre, Monóxido de Carbono, Monóxido de Nitrógeno, Dióxido de Nitrógeno, Partículas<2.5, Partículas<10, Óxidos de Nitrógeno, Ozono, Tolueno, Benceno, Etilbenceno, HidrocarburosTot, Metano, HidrocarburosNoMet, Temperatura, PuntoRocio, TempHumeda, HumedadRelativa, Precipitacion, Presion, VelViento, DirViento]
Index: []

[0 rows x 27 columns]

In [14]:
df_trafico.head()

      id  intensidad   año  mes  dia  hora
0  04002      143.75  2013    7    1     0
1  04002       78.75  2013    7    1     1
2  04002       86.75  2013    7    1     2
3  04002       39.25  2013    7    1     3
4  04002       13.50  2013    7    1     4

In [16]:
#Para los datos de trafico hay que hacer dos operaciones, Renombrar las variables temporales para que coincidan con el resto, y relacionar el id con la estacion a la que pertenece
#Para ello hay dos diccionarios segun el año, con diferentes id que relacionan la camara con la estacion más cercana
#Comenzare por cmabiar el nombre de las columnas
dic_col = {"intensidad":"Intensidad", "año":"Año","mes":"Mes","dia":"Dia","hora":"Hora"}
df_trafico = df_trafico.rename(columns=dic_col)

In [18]:
# lista_cctv = {4297, 1018:24, 5783:40, 6117:36, 4027:8,3891:49, 4754:18, 5064:56, 4839:17, 4124:47, 5365:54, 11038:16, 4436:48, 5772:38, 3910:11,
#             7017:50, 10184:39, 3787:60, 6610:57, 6333, 6342:27}
dic_id = {4436: '21014', 7017: '60002', 5772: '97021', 6333: '57002', 6117: '67012', 3787: '75407', 6610: '70015', 4754: '24020', 1018: '18XC82PM01',
         3891: '02044', 4839: '27001', 5064: '96019', 5783: '40001', 6342: '57011', 5365: '88009', 3910: '04002', 4124: '12017', 4297: '16019', 4027: '09011'}

In [20]:
dic_id_inv = {valor: clave for clave, valor in dic_id.items()}

In [22]:
dic_id_inv

{'21014': 4436,
 '60002': 7017,
 '97021': 5772,
 '57002': 6333,
 '67012': 6117,
 '75407': 3787,
 '70015': 6610,
 '24020': 4754,
 '18XC82PM01': 1018,
 '02044': 3891,
 '27001': 4839,
 '96019': 5064,
 '40001': 5783,
 '57011': 6342,
 '88009': 5365,
 '04002': 3910,
 '12017': 4124,
 '16019': 4297,
 '09011': 4027}

In [24]:
df_trafico["id2"]= df_trafico["id"].map(dic_id_inv)

In [26]:
df_trafico["id_final"] = df_trafico.apply(lambda row: row["id"] if pd.isna(row["id2"]) else row["id2"], axis=1)

In [27]:
df_trafico["id_final"] = df_trafico["id_final"].astype(int)

In [28]:
df_trafico["id_final"].isna().any()

False

In [29]:
# lista_cctv = {4297, 1018:24, 5783:40, 6117:36, 4027:8,3891:49, 4754:18, 5064:56, 4839:17, 4124:47, 5365:54, 11038:16, 4436:48, 5772:38, 3910:11,
#             7017:50, 10184:39, 3787:60, 6610:57, 6333, 6342:27}

In [30]:
for i in df_trafico["id_final"].unique():
    print(f"{i}: {df_trafico[df_trafico["id_final"]==i].size}")

3910: 766200
4027: 751208
4124: 707184
4297: 734576
1018: 730232
4436: 768600
4754: 745808
4839: 734640
5783: 744584
6333: 749240
6342: 758344
7017: 768824
6610: 751952
3787: 738048
5365: 753408
5772: 760296
3891: 695800
6117: 666096
5064: 669608
10184: 502880
11038: 138216

In [31]:
dic_cctv = {4297:35, 1018:24, 5783:40, 6117:36, 4027:8,3891:49, 4754:18, 5064:56, 4839:17, 4124:47, 5365:54, 11038:16, 4436:48, 5772:38, 3910:11,
            7017:50, 10184:39, 3787:60, 6610:57, 6333:55, 6342:27}

In [32]:
df_trafico

            id  Intensidad   Año  Mes  Dia  Hora     id2  id_final
0        04002      143.75  2013    7    1     0  3910.0      3910
1        04002       78.75  2013    7    1     1  3910.0      3910
2        04002       86.75  2013    7    1     2  3910.0      3910
3        04002       39.25  2013    7    1     3  3910.0      3910
4        04002       13.50  2013    7    1     4  3910.0      3910
...        ...         ...   ...  ...  ...   ...     ...       ...
1829463  11038      397.75  2024   12   31    19     NaN     11038
1829464  11038      387.50  2024   12   31    20     NaN     11038
1829465  11038      308.25  2024   12   31    21     NaN     11038
1829466  11038      153.00  2024   12   31    22     NaN     11038
1829467  11038       80.25  2024   12   31    23     NaN     11038

[1829468 rows x 8 columns]

In [40]:
df_trafico["id_final"].apply(lambda x: dic_cctv[x])

0          11
1          11
2          11
3          11
4          11
           ..
1829463    16
1829464    16
1829465    16
1829466    16
1829467    16
Name: id_final, Length: 1829468, dtype: int64

In [42]:
df_trafico = df_trafico.drop(columns=["id","id2"])
df_trafico = df_trafico.rename(columns={"id_final":"id"})
df_trafico["Estación"] = df_trafico["id"].apply(lambda x: dic_cctv[x])

In [46]:
df_trafico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1829468 entries, 0 to 1829467
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   Intensidad  float64
 1   Año         int64
 2   Mes         int64
 3   Dia         int64
 4   Hora        int64
 5   id          int32
 6   Estación    int64
dtypes: float64(1), int32(1), int64(5)
memory usage: 90.7 MB

In [54]:
#Comenzare un proceso para duplicar las filas con Etsaicon 35 y Estacion 55 ya que comparten camara con la 4 y la 59
df35 = df_trafico.loc[df_trafico["Estación"]==35].copy()
df55 = df_trafico.loc[df_trafico["Estación"]==55].copy()

In [56]:
df35["Estación"] = df35["Estación"].apply(lambda x: 4)
df55["Estación"] = df55["Estación"].apply(lambda x: 59)

In [66]:
df55

         Intensidad   Año  Mes  Dia  Hora    id  Estación
6109         132.00  2013    7    1     0  6333        59
6110          61.00  2013    7    1     1  6333        59
6111          73.00  2013    7    1     2  6333        59
6112          25.00  2013    7    1     3  6333        59
6113          27.00  2013    7    1     4  6333        59
...             ...   ...  ...  ...   ...   ...       ...
1825743      255.00  2024   12   31    19  6333        59
1825744      291.75  2024   12   31    20  6333        59
1825745      211.25  2024   12   31    21  6333        59
1825746       48.75  2024   12   31    22  6333        59
1825747       32.00  2024   12   31    23  6333        59

[93655 rows x 7 columns]

In [68]:
df_trafico = pd.concat([df_trafico, df35, df55], ignore_index=True)

In [70]:
df_trafico

         Intensidad   Año  Mes  Dia  Hora    id  Estación
0            143.75  2013    7    1     0  3910        11
1             78.75  2013    7    1     1  3910        11
2             86.75  2013    7    1     2  3910        11
3             39.25  2013    7    1     3  3910        11
4             13.50  2013    7    1     4  3910        11
...             ...   ...  ...  ...   ...   ...       ...
2014940      255.00  2024   12   31    19  6333        59
2014941      291.75  2024   12   31    20  6333        59
2014942      211.25  2024   12   31    21  6333        59
2014943       48.75  2024   12   31    22  6333        59
2014944       32.00  2024   12   31    23  6333        59

[2014945 rows x 7 columns]

In [76]:
df_trafico = df_trafico.drop(columns="id")

In [78]:
df_final = pd.merge(df_clima_contaminacion, df_trafico, how="left", on=["Estación", "Año", "Mes", "Dia","Hora"])

In [86]:
df_final[df_final.Intensidad.isna()].Hora.unique()

array([24, 17, 22, 23,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 16, 18,
       15, 19, 20, 21, 12, 13, 14], dtype=int64)

In [112]:
df_final[df_final.Estación==8]

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento,Intensidad
95136,8,2013,7,1,1,4.0,0.4,22.0,81.0,21.0,...,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0,171.75
95137,8,2013,7,1,2,3.0,0.2,2.0,33.0,13.0,...,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6,142.00
95138,8,2013,7,1,3,3.0,0.2,3.0,31.0,12.0,...,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6,84.75
95139,8,2013,7,1,4,3.0,0.2,1.0,21.0,9.0,...,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5,67.75
95140,8,2013,7,1,5,3.0,0.2,1.0,11.0,12.0,...,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3,55.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195547,8,2024,12,31,20,1.0,0.4,2.0,73.0,8.0,...,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4,66.75
195548,8,2024,12,31,21,2.0,0.5,12.0,84.0,15.0,...,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9,158.75
195549,8,2024,12,31,22,3.0,0.5,14.0,80.0,17.0,...,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7,116.00
195550,8,2024,12,31,23,2.0,0.6,11.0,74.0,19.0,...,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5,95.50
195551,8,2024,12,31,24,3.0,0.6,22.0,81.0,20.0,...,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5,NaN

In [98]:
df_final.groupby(['Estación', 'Hora'])['Intensidad'].transform(lambda x: x.fillna(x.mean()))

AttributeError: 'numpy.bool_' object has no attribute 'value_counts'

In [102]:
df_final.groupby('Estación')['Intensidad'].apply(lambda x: x.isnull().sum())

Estación
4      12547
8      10857
11      9003
16     81867
17     12881
18     11453
24     13353
27     10005
35     12593
36     21023
38      9754
39     40607
40     11648
47     16054
48      8774
49     17505
50      8750
54     10594
55     11087
56     20665
57     10766
58    100800
59     11070
60     12474
Name: Intensidad, dtype: int64

In [116]:
df_clima_contaminacion[df_clima_contaminacion.Estación==8]

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,Metano,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
95136,8,2013,7,1,1,4.0,0.4,22.0,81.0,21.0,...,0.0,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0
95137,8,2013,7,1,2,3.0,0.2,2.0,33.0,13.0,...,0.0,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6
95138,8,2013,7,1,3,3.0,0.2,3.0,31.0,12.0,...,0.0,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6
95139,8,2013,7,1,4,3.0,0.2,1.0,21.0,9.0,...,0.0,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5
95140,8,2013,7,1,5,3.0,0.2,1.0,11.0,12.0,...,0.0,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195547,8,2024,12,31,20,1.0,0.4,2.0,73.0,8.0,...,0.0,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4
195548,8,2024,12,31,21,2.0,0.5,12.0,84.0,15.0,...,0.0,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9
195549,8,2024,12,31,22,3.0,0.5,14.0,80.0,17.0,...,0.0,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7
195550,8,2024,12,31,23,2.0,0.6,11.0,74.0,19.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5
195551,8,2024,12,31,24,3.0,0.6,22.0,81.0,20.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5

In [118]:
df_clima

,Año,Mes,Dia,Hora,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,2013,1,1,1.0,1.13,0.83,0.98,97.72,10.04,92.71,2.03,219.2
1,2013,1,1,2.0,0.96,0.67,0.82,97.99,5.90,92.68,1.59,231.9
2,2013,1,1,3.0,1.05,0.79,0.92,98.00,1.85,92.66,1.21,252.6
3,2013,1,1,4.0,1.00,0.91,0.95,99.27,0.85,92.67,0.86,273.3
4,2013,1,1,5.0,0.79,0.93,0.86,100.00,0.66,92.70,0.90,293.7
...,...,...,...,...,...,...,...,...,...,...,...,...
105187,2024,12,31,20.0,2.58,-1.86,0.36,72.42,0.00,93.83,1.26,26.4
105188,2024,12,31,21.0,1.92,-2.30,-0.19,73.36,0.00,93.85,1.28,40.9
105189,2024,12,31,22.0,1.45,-2.50,-0.52,74.79,0.00,93.88,1.26,54.7
105190,2024,12,31,23.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5
105191,2024,12,31,24.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5

In [146]:
año = 2013
meses = [1, 2, 3, 4, 5, 6]
filtro = (df_clima["Año"]==año) & (df_clima["Mes"].isin(meses))
df_clima = df_clima[~filtro]

In [148]:
df_clima

,Año,Mes,Dia,Hora,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
4344,2013,7,1,1.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0
4345,2013,7,1,2.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6
4346,2013,7,1,3.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6
4347,2013,7,1,4.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5
4348,2013,7,1,5.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3
...,...,...,...,...,...,...,...,...,...,...,...,...
105187,2024,12,31,20.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4
105188,2024,12,31,21.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9
105189,2024,12,31,22.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7
105190,2024,12,31,23.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5
105191,2024,12,31,24.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5

In [134]:
df_contaminacion[df_contaminacion.Estación==35]

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,Partículas<10,Óxidos de Nitrógeno,Ozono,Tolueno,Benceno,Etilbenceno,HidrocarburosTot,Metano,HidrocarburosNoMet
795840,35,2013,7,1,1,5.0,0.6,41.0,100.0,0.0,0.0,163.0,19.87,0.0,0.0,0.0,0.0,0.0,0.0
795841,35,2013,7,1,2,3.0,0.2,3.0,43.0,0.0,0.0,48.0,51.25,0.0,0.0,0.0,0.0,0.0,0.0
795842,35,2013,7,1,3,4.0,0.2,5.0,38.0,0.0,0.0,46.0,53.68,0.0,0.0,0.0,0.0,0.0,0.0
795843,35,2013,7,1,4,3.0,0.2,4.0,30.0,0.0,0.0,36.0,58.37,0.0,0.0,0.0,0.0,0.0,0.0
795844,35,2013,7,1,5,3.0,0.1,4.0,19.0,0.0,0.0,25.0,66.30,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894547,35,2024,12,31,20,6.0,0.7,8.0,82.0,0.0,0.0,94.0,8.00,0.0,0.0,0.0,0.0,0.0,0.0
894548,35,2024,12,31,21,6.0,0.6,7.0,67.0,0.0,0.0,77.0,8.00,0.0,0.0,0.0,0.0,0.0,0.0
894549,35,2024,12,31,22,6.0,0.7,10.0,69.0,0.0,0.0,84.0,7.00,0.0,0.0,0.0,0.0,0.0,0.0
894550,35,2024,12,31,23,5.0,0.7,49.0,68.0,0.0,0.0,143.0,5.00,0.0,0.0,0.0,0.0,0.0,0.0
894551,35,2024,12,31,24,5.0,0.8,41.0,64.0,0.0,0.0,127.0,2.00,0.0,0.0,0.0,0.0,0.0,0.0

In [140]:
df_contaminacion.groupby('Estación').Año.count()

Estación
4      95136
8     100416
11     99504
16     98424
17    100848
18    100248
24    100416
27    100848
35     98712
36    100248
38    100512
39    100752
40    100776
47    100584
48    100824
49    100848
50    100848
54    100848
55    100848
56    100656
57    100824
58    100800
59    100440
60    100848
Name: Año, dtype: int64

In [174]:
df_prueba = pd.merge(df_contaminacion[df_contaminacion.Estación==4], df_clima, how="right", on=["Año","Mes","Dia","Hora"])

In [182]:
df_prueba

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,Metano,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,4.0,2013,7,1,1.0,5.0,0.5,48.0,112.0,0.0,...,0.0,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0
1,4.0,2013,7,1,2.0,5.0,0.6,79.0,116.0,0.0,...,0.0,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6
2,4.0,2013,7,1,3.0,4.0,0.3,6.0,47.0,0.0,...,0.0,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6
3,4.0,2013,7,1,4.0,3.0,0.2,3.0,25.0,0.0,...,0.0,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5
4,4.0,2013,7,1,5.0,3.0,0.2,3.0,10.0,0.0,...,0.0,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100843,4.0,2024,12,31,20.0,0.0,0.4,7.0,74.0,0.0,...,0.0,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4
100844,4.0,2024,12,31,21.0,0.0,0.6,52.0,81.0,0.0,...,0.0,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9
100845,4.0,2024,12,31,22.0,0.0,0.6,81.0,85.0,0.0,...,0.0,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7
100846,4.0,2024,12,31,23.0,0.0,0.4,25.0,60.0,0.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5
100847,4.0,2024,12,31,24.0,0.0,0.3,5.0,45.0,0.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5

In [198]:
df_contaminacion.Estación.unique().shape

(24,)

In [210]:
df_final = pd.DataFrame()
for i in df_contaminacion.Estación.unique():
    df_prueba = pd.merge(df_contaminacion[df_contaminacion.Estación==i], df_clima, how="right", on=["Año","Mes","Dia","Hora"])
    df_prueba["Estación"] = df_prueba["Estación"].apply(lambda x: i)
    df_final = pd.concat([df_final,df_prueba], ignore_index=True)

In [214]:
df_final

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,Metano,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento
0,4,2013,7,1,1.0,5.0,0.5,48.0,112.0,0.0,...,0.0,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0
1,4,2013,7,1,2.0,5.0,0.6,79.0,116.0,0.0,...,0.0,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6
2,4,2013,7,1,3.0,4.0,0.3,6.0,47.0,0.0,...,0.0,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6
3,4,2013,7,1,4.0,3.0,0.2,3.0,25.0,0.0,...,0.0,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5
4,4,2013,7,1,5.0,3.0,0.2,3.0,10.0,0.0,...,0.0,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2420347,60,2024,12,31,20.0,0.0,0.0,16.0,65.0,0.0,...,0.0,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4
2420348,60,2024,12,31,21.0,0.0,0.0,33.0,77.0,0.0,...,0.0,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9
2420349,60,2024,12,31,22.0,0.0,0.0,29.0,68.0,0.0,...,0.0,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7
2420350,60,2024,12,31,23.0,0.0,0.0,7.0,47.0,0.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5
2420351,60,2024,12,31,24.0,0.0,0.0,3.0,36.0,0.0,...,0.0,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5

In [230]:
col_na = df_final.columns[df_final.isna().any()].tolist()

In [238]:
df_final[col_na] = df_final.groupby(['Estación', 'Hora'])[col_na].transform(lambda x: x.fillna(x.mean()))

In [240]:
df_final.isna().any()

Estación                 False
Año                      False
Mes                      False
Dia                      False
Hora                     False
Dióxido de Azufre        False
Monóxido de Carbono      False
Monóxido de Nitrógeno    False
Dióxido de Nitrógeno     False
Partículas<2.5           False
Partículas<10            False
Óxidos de Nitrógeno      False
Ozono                    False
Tolueno                  False
Benceno                  False
Etilbenceno              False
HidrocarburosTot         False
Metano                   False
HidrocarburosNoMet       False
Temperatura              False
PuntoRocio               False
TempHumeda               False
HumedadRelativa          False
Precipitacion            False
Presion                  False
VelViento                False
DirViento                False
dtype: bool

In [244]:
df = pd.merge(df_final, df_trafico, on=["Estación","Año","Mes","Dia","Hora"], how="left")

In [246]:
df

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento,Intensidad
0,4,2013,7,1,1.0,5.0,0.5,48.0,112.0,0.0,...,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0,374.25
1,4,2013,7,1,2.0,5.0,0.6,79.0,116.0,0.0,...,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6,402.50
2,4,2013,7,1,3.0,4.0,0.3,6.0,47.0,0.0,...,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6,243.00
3,4,2013,7,1,4.0,3.0,0.2,3.0,25.0,0.0,...,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5,174.50
4,4,2013,7,1,5.0,3.0,0.2,3.0,10.0,0.0,...,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3,187.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2420347,60,2024,12,31,20.0,0.0,0.0,16.0,65.0,0.0,...,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4,54.50
2420348,60,2024,12,31,21.0,0.0,0.0,33.0,77.0,0.0,...,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9,49.00
2420349,60,2024,12,31,22.0,0.0,0.0,29.0,68.0,0.0,...,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7,9.75
2420350,60,2024,12,31,23.0,0.0,0.0,7.0,47.0,0.0,...,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5,21.50
2420351,60,2024,12,31,24.0,0.0,0.0,3.0,36.0,0.0,...,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5,NaN

In [248]:
df.isna().any()

Estación                 False
Año                      False
Mes                      False
Dia                      False
Hora                     False
Dióxido de Azufre        False
Monóxido de Carbono      False
Monóxido de Nitrógeno    False
Dióxido de Nitrógeno     False
Partículas<2.5           False
Partículas<10            False
Óxidos de Nitrógeno      False
Ozono                    False
Tolueno                  False
Benceno                  False
Etilbenceno              False
HidrocarburosTot         False
Metano                   False
HidrocarburosNoMet       False
Temperatura              False
PuntoRocio               False
TempHumeda               False
HumedadRelativa          False
Precipitacion            False
Presion                  False
VelViento                False
DirViento                False
Intensidad                True
dtype: bool

In [254]:
df.groupby(["Estación"])["Intensidad"].apply(lambda x: x.isna().sum())

Estación
4      12852
8      10875
11      9059
16     84291
17     12881
18     11503
24     13371
27     10005
35     12852
36     21048
38      9774
39     40611
40     11651
47     16111
48      8775
49     17505
50      8750
54     10594
55     11087
56     20673
57     10767
58    100848
59     11087
60     12474
Name: Intensidad, dtype: int64

In [258]:
index_eliminar_58 = df[df.Estación==58].index #Cojo los indices de la estacion 58 que es la del pardo que no la usare para eliminarlos del df

In [260]:
df = df.drop(index_eliminar_58)

In [262]:
df.groupby(["Estación"])["Intensidad"].apply(lambda x: x.isna().sum())

Estación
4     12852
8     10875
11     9059
16    84291
17    12881
18    11503
24    13371
27    10005
35    12852
36    21048
38     9774
39    40611
40    11651
47    16111
48     8775
49    17505
50     8750
54    10594
55    11087
56    20673
57    10767
59    11087
60    12474
Name: Intensidad, dtype: int64

In [272]:
df[df.Estación==8].head(40)

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento,Intensidad
100848,8,2013,7,1,1.0,4.0,0.4,22.0,81.0,21.0,...,0.0,16.99,7.98,12.48,55.35,0.00,92.79,1.04,118.0,171.75
100849,8,2013,7,1,2.0,3.0,0.2,2.0,33.0,13.0,...,0.0,15.90,7.93,11.92,59.08,0.00,92.78,1.11,115.6,142.00
100850,8,2013,7,1,3.0,3.0,0.2,3.0,31.0,12.0,...,0.0,15.09,7.93,11.51,62.16,0.00,92.79,1.26,107.6,84.75
100851,8,2013,7,1,4.0,3.0,0.2,1.0,21.0,9.0,...,0.0,14.45,8.01,11.23,65.06,0.00,92.81,1.48,100.5,67.75
100852,8,2013,7,1,5.0,3.0,0.2,1.0,11.0,12.0,...,0.0,15.28,8.31,11.80,63.04,0.00,92.83,2.28,97.3,55.50
100853,8,2013,7,1,6.0,3.0,0.2,2.0,22.0,13.0,...,0.0,17.56,8.22,12.89,54.16,0.00,92.83,2.68,99.2,190.50
100854,8,2013,7,1,7.0,3.0,0.2,4.0,38.0,13.0,...,0.0,20.50,8.24,14.37,45.14,0.00,92.83,2.64,108.8,505.25
100855,8,2013,7,1,8.0,4.0,0.4,23.0,67.0,16.0,...,0.0,23.60,8.28,15.94,37.45,0.00,92.80,2.52,122.2,764.50
100856,8,2013,7,1,9.0,5.0,0.5,52.0,79.0,21.0,...,0.0,26.70,7.93,17.32,30.46,0.00,92.77,2.24,138.1,703.75
100857,8,2013,7,1,10.0,5.0,0.5,31.0,62.0,20.0,...,0.0,29.79,6.56,18.17,23.15,0.00,92.74,2.12,157.3,624.50
100858,8,2013,7,1,11.0,4.0,0.4,23.0,42.0,14.0,...,0.0,31.63,5.76,18.70,19.72,0.00,92.68,2.10,165.1,709.25
100859,8,2013,7,1,12.0,4.0,0.3,17.0,31.0,14.0,...,0.0,32.70,5.31,19.01,18.01,0.00,92.62,2.14,167.3,617.50
100860,8,2013,7,1,13.0,3.0,0.2,9.0,23.0,12.0,...,0.0,33.20,4.99,19.10,17.12,0.00,92.55,2.19,169.8,542.00
100861,8,2013,7,1,14.0,4.0,0.3,16.0,34.0,14.0,...,0.0,33.24,4.72,18.98,16.78,0.05,92.49,2.16,172.3,514.75
100862,8,2013,7,1,15.0,4.0,0.3,17.0,33.0,14.0,...,0.0,32.76,4.66,18.71,17.17,0.94,92.44,1.86,179.7,513.00
100863,8,2013,7,1,16.0,4.0,0.3,12.0,25.0,12.0,...,0.0,31.82,4.93,18.38,18.48,3.79,92.42,1.31,201.1,458.75
100864,8,2013,7,1,17.0,4.0,0.3,14.0,32.0,13.0,...,0.0,30.41,5.67,18.04,21.18,5.46,92.42,1.04,258.9,479.50
100865,8,2013,7,1,18.0,4.0,0.4,18.0,37.0,15.0,...,0.0,28.16,8.98,18.57,30.38,1.69,92.47,1.31,307.2,525.50
100866,8,2013,7,1,19.0,4.0,0.3,7.0,38.0,15.0,...,0.0,25.15,10.55,17.85,40.03,1.56,92.54,1.82,328.2,498.50
100867,8,2013,7,1,20.0,3.0,0.3,8.0,40.0,11.0,...,0.0,23.42,11.09,17.26,45.98,1.33,92.63,3.07,342.7,522.25
100868,8,2013,7,1,21.0,4.0,0.5,17.0,68.0,14.0,...,0.0,22.09,12.03,17.06,52.92,0.81,92.69,3.53,357.9,365.25
100869,8,2013,7,1,22.0,3.0,0.3,6.0,47.0,14.0,...,0.0,21.10,12.57,16.83,58.11,0.33,92.71,3.24,18.7,301.75
100870,8,2013,7,1,23.0,3.0,0.3,3.0,28.0,14.0,...,0.0,20.60,12.62,16.61,60.17,0.09,92.70,2.93,42.0,292.00
100871,8,2013,7,1,24.0,3.0,0.3,4.0,30.0,13.0,...,0.0,20.20,12.55,16.38,61.34,0.02,92.67,2.50,65.9,NaN
100872,8,2013,7,2,1.0,3.0,0.2,4.0,21.0,12.0,...,0.0,19.67,12.21,15.94,62.00,0.00,92.62,2.06,87.5,152.50
100873,8,2013,7,2,2.0,3.0,0.2,7.0,24.0,11.0,...,0.0,18.77,11.78,15.28,63.72,0.00,92.58,1.69,105.1,110.25
100874,8,2013,7,2,3.0,3.0,0.2,2.0,21.0,8.0,...,0.0,17.74,11.60,14.67,67.12,0.00,92.60,1.63,112.3,68.00
100875,8,2013,7,2,4.0,3.0,0.2,3.0,22.0,12.0,...,0.0,16.51,11.63,14.07,72.67,0.00,92.63,1.24,109.3,48.50
100876,8,2013,7,2,5.0,4.0,0.2,6.0,17.0,9.0,...,0.0,16.72,11.81,14.26,72.67,0.00,92.68,1.69,94.1,67.50
100877,8,2013,7,2,6.0,3.0,0.2,4.0,13.0,13.0,...,0.0,18.60,11.58,15.09,63.54,0.00,92.72,1.83,98.8,125.25
100878,8,2013,7,2,7.0,4.0,0.2,9.0,18.0,16.0,...,0.0,21.46,10.79,16.12,50.59,0.00,92.74,1.13,117.5,478.50
100879,8,2013,7,2,8.0,4.0,0.3,23.0,38.0,14.0,...,0.0,24.90,9.26,17.08,37.07,0.00,92.75,0.74,203.1,795.75
100880,8,2013,7,2,9.0,4.0,0.4,26.0,48.0,17.0,...,0.0,27.80,8.17,17.98,29.02,0.00,92.74,1.28,225.9,761.75
100881,8,2013,7,2,10.0,4.0,0.4,33.0,49.0,17.0,...,0.0,29.83,7.23,18.53,24.25,0.00,92.73,1.57,231.5,689.50
100882,8,2013,7,2,11.0,4.0,0.3,15.0,26.0,14.0,...,0.0,31.29,6.50,18.89,21.24,0.00,92.71,1.87,229.6,564.25
100883,8,2013,7,2,12.0,4.0,0.3,19.0,34.0,15.0,...,0.0,32.20,6.16,19.18,19.70,0.00,92.67,2.13,227.1,546.25
100884,8,2013,7,2,13.0,4.0,0.4,21.0,35.0,15.0,...,0.0,32.65,6.02,19.34,19.02,0.00,92.64,2.28,228.2,574.00
100885,8,2013,7,2,14.0,4.0,0.3,14.0,31.0,14.0,...,0.0,32.80,5.87,19.33,18.65,0.00,92.61,2.35,232.8,595.75
100886,8,2013,7,2,15.0,4.0,0.4,18.0,42.0,15.0,...,0.0,32.82,5.62,19.22,18.30,0.00,92.58,2.36,241.2,590.50
100887,8,2013,7,2,16.0,4.0,0.3,13.0,35.0,15.0,...,0.0,32.40,5.41,18.90,18.46,0.00,92.57,2.30,251.5,516.00

In [268]:
df[df.Estación==16].tail(40)

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento,Intensidad
403352,16,2024,12,30,9.0,0.0,0.0,21.0,30.0,0.0,...,0.0,2.83,0.98,1.90,87.46,0.00,93.92,1.68,74.5,409.25
403353,16,2024,12,30,10.0,0.0,0.0,23.0,34.0,0.0,...,0.0,4.80,1.73,3.26,80.51,0.00,93.94,1.33,96.5,451.25
403354,16,2024,12,30,11.0,0.0,0.0,12.0,22.0,0.0,...,0.0,6.57,2.17,4.37,73.48,0.00,93.88,1.27,123.4,498.75
403355,16,2024,12,30,12.0,0.0,0.0,6.0,17.0,0.0,...,0.0,8.29,2.33,5.31,66.09,0.00,93.80,1.41,143.4,558.75
403356,16,2024,12,30,13.0,0.0,0.0,6.0,16.0,0.0,...,0.0,9.37,2.00,5.68,59.98,0.00,93.73,1.49,151.2,515.75
403357,16,2024,12,30,14.0,0.0,0.0,6.0,21.0,0.0,...,0.0,9.34,1.81,5.58,59.19,0.00,93.69,1.26,153.6,462.75
403358,16,2024,12,30,15.0,0.0,0.0,3.0,13.0,0.0,...,0.0,8.52,2.40,5.46,65.38,0.00,93.68,0.71,152.4,466.75
403359,16,2024,12,30,16.0,0.0,0.0,1.0,12.0,0.0,...,0.0,6.66,1.60,4.13,70.12,0.00,93.69,0.30,181.9,439.00
403360,16,2024,12,30,17.0,0.0,0.0,1.0,15.0,0.0,...,0.0,5.45,1.10,3.27,73.43,0.00,93.71,0.22,309.5,527.50
403361,16,2024,12,30,18.0,0.0,0.0,8.0,30.0,0.0,...,0.0,4.20,1.11,2.65,80.16,0.00,93.74,0.67,346.2,542.00
403362,16,2024,12,30,19.0,0.0,0.0,20.0,49.0,0.0,...,0.0,2.92,1.08,2.00,87.57,0.00,93.78,0.97,0.0,505.75
403363,16,2024,12,30,20.0,0.0,0.0,37.0,55.0,0.0,...,0.0,1.73,1.00,1.36,94.69,0.00,93.79,1.10,11.5,426.00
403364,16,2024,12,30,21.0,0.0,0.0,66.0,59.0,0.0,...,0.0,0.95,0.90,0.93,99.47,0.00,93.80,1.16,23.5,348.50
403365,16,2024,12,30,22.0,0.0,0.0,114.0,62.0,0.0,...,0.0,0.45,0.75,0.60,100.00,0.00,93.80,1.20,35.8,288.00
403366,16,2024,12,30,23.0,0.0,0.0,114.0,66.0,0.0,...,0.0,0.01,0.51,0.26,100.00,0.00,93.79,1.22,47.0,223.00
403367,16,2024,12,30,24.0,0.0,0.0,21.0,37.0,0.0,...,0.0,-0.31,0.21,-0.05,100.00,0.00,93.77,1.23,54.9,NaN
403368,16,2024,12,31,1.0,0.0,0.0,1.0,14.0,0.0,...,0.0,-0.58,-0.13,-0.36,100.00,0.02,93.75,1.23,59.7,114.75
403369,16,2024,12,31,2.0,0.0,0.0,2.0,20.0,0.0,...,0.0,-0.74,-0.44,-0.59,100.00,0.02,93.75,1.23,62.8,91.00
403370,16,2024,12,31,3.0,0.0,0.0,3.0,13.0,0.0,...,0.0,-0.79,-0.76,-0.77,100.00,0.02,93.75,1.21,63.0,76.00
403371,16,2024,12,31,4.0,0.0,0.0,1.0,8.0,0.0,...,0.0,-0.85,-1.05,-0.95,99.26,0.00,93.76,1.20,62.2,57.00
403372,16,2024,12,31,5.0,0.0,0.0,1.0,7.0,0.0,...,0.0,-0.93,-1.28,-1.11,98.35,0.00,93.78,1.19,61.3,65.75
403373,16,2024,12,31,6.0,0.0,0.0,1.0,7.0,0.0,...,0.0,-1.01,-1.45,-1.23,97.70,0.00,93.81,1.18,61.0,102.00
403374,16,2024,12,31,7.0,0.0,0.0,1.0,10.0,0.0,...,0.0,-1.05,-1.52,-1.29,97.51,0.01,93.83,1.16,60.1,150.25
403375,16,2024,12,31,8.0,0.0,0.0,1.0,14.0,0.0,...,0.0,0.98,-0.80,0.09,87.88,0.01,93.86,0.99,58.2,211.25
403376,16,2024,12,31,9.0,0.0,0.0,2.0,16.0,0.0,...,0.0,4.11,-0.37,1.87,72.56,0.00,93.90,1.90,57.5,295.00
403377,16,2024,12,31,10.0,0.0,0.0,17.0,34.0,0.0,...,0.0,6.40,0.05,3.23,63.75,0.00,93.92,1.61,70.0,376.25
403378,16,2024,12,31,11.0,0.0,0.0,7.0,20.0,0.0,...,0.0,8.84,0.21,4.53,54.60,0.00,93.88,1.49,92.3,436.00
403379,16,2024,12,31,12.0,0.0,0.0,3.0,13.0,0.0,...,0.0,9.87,0.25,5.06,51.27,0.00,93.79,1.48,99.7,490.25
403380,16,2024,12,31,13.0,0.0,0.0,5.0,16.0,0.0,...,0.0,10.35,0.17,5.26,49.24,0.00,93.71,1.45,101.5,524.00
403381,16,2024,12,31,14.0,0.0,0.0,6.0,18.0,0.0,...,0.0,10.32,0.17,5.24,49.32,0.00,93.66,1.35,100.2,499.75
403382,16,2024,12,31,15.0,0.0,0.0,2.0,13.0,0.0,...,0.0,9.48,1.93,5.70,59.37,0.00,93.65,0.76,101.5,395.25
403383,16,2024,12,31,16.0,0.0,0.0,2.0,11.0,0.0,...,0.0,7.89,0.17,4.03,58.25,0.00,93.67,0.33,115.0,334.00
403384,16,2024,12,31,17.0,0.0,0.0,1.0,12.0,0.0,...,0.0,6.61,-0.73,2.94,59.47,0.00,93.71,0.33,0.0,332.50
403385,16,2024,12,31,18.0,0.0,0.0,1.0,20.0,0.0,...,0.0,4.99,-0.93,2.03,65.54,0.00,93.76,0.85,1.3,324.50
403386,16,2024,12,31,19.0,0.0,0.0,18.0,46.0,0.0,...,0.0,3.60,-1.34,1.13,70.20,0.00,93.80,1.17,11.3,397.75
403387,16,2024,12,31,20.0,0.0,0.0,38.0,65.0,0.0,...,0.0,2.58,-1.86,0.36,72.42,0.00,93.83,1.26,26.4,387.50
403388,16,2024,12,31,21.0,0.0,0.0,102.0,70.0,0.0,...,0.0,1.92,-2.30,-0.19,73.36,0.00,93.85,1.28,40.9,308.25
403389,16,2024,12,31,22.0,0.0,0.0,54.0,63.0,0.0,...,0.0,1.45,-2.50,-0.52,74.79,0.00,93.88,1.26,54.7,153.00
403390,16,2024,12,31,23.0,0.0,0.0,67.0,64.0,0.0,...,0.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5,80.25
403391,16,2024,12,31,24.0,0.0,0.0,8.0,42.0,0.0,...,0.0,1.00,-2.44,-0.72,77.49,0.00,93.90,1.26,67.5,NaN

In [274]:
df.to_csv("datos_finales_nan.csv", index=False)

In [278]:
df

,Estación,Año,Mes,Dia,Hora,Dióxido de Azufre,Monóxido de Carbono,Monóxido de Nitrógeno,Dióxido de Nitrógeno,Partículas<2.5,...,HidrocarburosNoMet,Temperatura,PuntoRocio,TempHumeda,HumedadRelativa,Precipitacion,Presion,VelViento,DirViento,Intensidad
0,4,2013,7,1,1.0,5.0,0.5,48.0,112.0,0.0,...,0.0,16.99,7.98,12.48,55.35,0.0,92.79,1.04,118.0,374.25
1,4,2013,7,1,2.0,5.0,0.6,79.0,116.0,0.0,...,0.0,15.90,7.93,11.92,59.08,0.0,92.78,1.11,115.6,402.50
2,4,2013,7,1,3.0,4.0,0.3,6.0,47.0,0.0,...,0.0,15.09,7.93,11.51,62.16,0.0,92.79,1.26,107.6,243.00
3,4,2013,7,1,4.0,3.0,0.2,3.0,25.0,0.0,...,0.0,14.45,8.01,11.23,65.06,0.0,92.81,1.48,100.5,174.50
4,4,2013,7,1,5.0,3.0,0.2,3.0,10.0,0.0,...,0.0,15.28,8.31,11.80,63.04,0.0,92.83,2.28,97.3,187.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2420347,60,2024,12,31,20.0,0.0,0.0,16.0,65.0,0.0,...,0.0,2.58,-1.86,0.36,72.42,0.0,93.83,1.26,26.4,54.50
2420348,60,2024,12,31,21.0,0.0,0.0,33.0,77.0,0.0,...,0.0,1.92,-2.30,-0.19,73.36,0.0,93.85,1.28,40.9,49.00
2420349,60,2024,12,31,22.0,0.0,0.0,29.0,68.0,0.0,...,0.0,1.45,-2.50,-0.52,74.79,0.0,93.88,1.26,54.7,9.75
2420350,60,2024,12,31,23.0,0.0,0.0,7.0,47.0,0.0,...,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5,21.50
2420351,60,2024,12,31,24.0,0.0,0.0,3.0,36.0,0.0,...,0.0,1.00,-2.44,-0.72,77.49,0.0,93.90,1.26,67.5,NaN